# Generated by Django 4.2 on 2023-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='tel',
            field=models.TextField(blank=True),
        ),
    ]
