# Generated by Django 4.2 on 2023-08-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBapp', '0002_alter_hospital_tel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
