# Generated by Django 4.2.4 on 2023-08-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='reply',
        ),
    ]
