# Generated by Django 4.2.4 on 2023-08-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '__first__'),
        ('doctor', '0007_remove_doctor_answer_alter_doctor_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoranswer',
            name='board_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
