# Generated by Django 4.2 on 2023-08-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '__first__'),
        ('doctor', '0009_alter_doctoranswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoranswer',
            name='board_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
