# Generated by Django 4.2 on 2023-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctoranswer_board_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='introduction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
