# Generated by Django 4.2.3 on 2023-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_myuser_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="questions",
            field=models.ManyToManyField(blank=True, to="board.board"),
        ),
    ]
