# Generated by Django 4.2.3 on 2023-07-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='questions',
        ),
    ]
